-- 

DROP TABLE PUBLIC.ENDERECOCLIENTE;

DROP TABLE PUBLIC.CLIENTE;

DROP TABLE PUBLIC.PRODUTO;

DROP TABLE PUBLIC.CATEGORIA;

DROP TABLE PUBLIC.PRODUTOCATEGORIA;

DROP TABLE PUBLIC.PEDIDO;

DROP TABLE PUBLIC.PEDIDOITEM;

DROP TABLE PUBLIC.MOVIMENTOPEDIDO;

DROP TABLE PUBLIC.PEDIDOITEM;

DROP TABLE PUBLIC.FATURA;

DROP TABLE PUBLIC.PAGAMENTOPIX;

DROP TABLE PUBLIC.PAGAMENTOCARTAOCREDITO;

DROP TABLE PUBLIC.PAGAMENTO;

DROP TABLE PUBLIC.METODOPAGAMENTOPIX;

DROP TABLE PUBLIC.METODOPAGAMENTOCARTAOCREDITO;

DROP TABLE PUBLIC.METODOPAGAMENTO;